# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stock.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bstock.proto\x12\x05stock\"\'\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"-\n\x19ProductStockCheckResponse\x12\x10\n\x08isEnough\x18\x03 \x01(\x08\"/\n\x1aProductStockReduceResponse\x12\x11\n\tisSuccess\x18\x04 \x01(\x08\x32\x89\x01\n\x05Stock\x12>\n\nCheckStock\x12\x0e.stock.Product\x1a .stock.ProductStockCheckResponse\x12@\n\x0bReduceStock\x12\x0e.stock.Product\x1a!.stock.ProductStockReduceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'stock_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRODUCT']._serialized_start=22
  _globals['_PRODUCT']._serialized_end=61
  _globals['_PRODUCTSTOCKCHECKRESPONSE']._serialized_start=63
  _globals['_PRODUCTSTOCKCHECKRESPONSE']._serialized_end=108
  _globals['_PRODUCTSTOCKREDUCERESPONSE']._serialized_start=110
  _globals['_PRODUCTSTOCKREDUCERESPONSE']._serialized_end=157
  _globals['_STOCK']._serialized_start=160
  _globals['_STOCK']._serialized_end=297
# @@protoc_insertion_point(module_scope)
