# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transaction.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transaction.proto\x12\x0btransaction\"F\n\x12TransactionMessage\x12\x10\n\x08receiver\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x02\"(\n\x13TransactionResponse\x12\x11\n\tisSuccess\x18\x04 \x01(\x08\x32\x63\n\x0bTransaction\x12T\n\x0fMakeTransaction\x12\x1f.transaction.TransactionMessage\x1a .transaction.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTIONMESSAGE']._serialized_start=34
  _globals['_TRANSACTIONMESSAGE']._serialized_end=104
  _globals['_TRANSACTIONRESPONSE']._serialized_start=106
  _globals['_TRANSACTIONRESPONSE']._serialized_end=146
  _globals['_TRANSACTION']._serialized_start=148
  _globals['_TRANSACTION']._serialized_end=247
# @@protoc_insertion_point(module_scope)
